### PR TITLE
Phase1final

### PR DESCRIPTION
**Pull request by StevenMccracken**

### CODE REVIEW

**Comment by BryanDiNardo** [comment]
Should I have a class description for Drug and Skill?

On Mon, Apr 18, 2016 at 12:29 PM, Steven McCracken <notifications@github.com

**Comment by StevenMccracken** [comment]
Nope, he didn’t ask about it last time so it’s all good. I finalized everything

**Comment by BryanDiNardo** [comment]
Alright I just tweaked your final submission and added arrows indicating
direction of the relationship verb. Now I'm going to submit the class
descriptions and everything should be ready to turn in

**Comment by StevenMccracken** [comment]
Don’t touch anything else, I fixed it all up

**Comment by StevenMccracken** [comment]
Take a look at the Project specifications document. That’s what i’m submitting along with the uml class diagram

**Comment by BryanDiNardo** [comment]
Not letting me submit my class descriptions since you're probably working
on master branch. So here, I'm sending you the doc directly

**Comment by BryanDiNardo** [comment]
And no I got rid of some classes for the class descriptions and updated the
business rules so that Project Specifications document isn't correct

**Comment by StevenMccracken** [comment]
Okay send it to me

**Pull request merged**
